# Exercises for modules 1 and 2

Base Python revision and NumPy.


In [72]:
# library
import numpy as np
import pandas as pd 
import random 

## Exercise 1 (Python review)

Our task is to do some operations on the made-up products database

In [73]:
# We store product database ID, SKU, price, category, stock amount
products = [(1, 'Wireless Mouse', 'WMA-123', 29.99, 'Electronics', 150),
            (2, 'Keyboard', 'KBD-200', 129.99, 'Electronics', 200),
            (3, 'Yamaha Classical Guitar', 'CGT-467', 550.99, 'Music', 190),
            (4, 'Gibson Les Paul', 'FLP-467', 2000.0, 'Music', 3),
            (5, 'Fender Stratocaster', 'FST-111', 3000.0, 'Music', 50),
            (6, 'Sony Trinitron Color CRT TV | Vintage', 'KV-1380R 13', 368.0, 'Electronics', 5)]

1. Create function `avarage_price()` that will return avarage products price
2. Create function `categories()` that will return all product categories
3. Create function `min_max()` that will return minimal and maximal product prices.

In [74]:
df = pd.DataFrame(products)
df.columns=["ID","Product", "SKU", "price", "category", "stock amount"]

In [77]:
def avarage_price(x=df["price"]):
    return np.mean(x).round(2)
print(f"1. Average price: {avarage_price()}")
def categories(x=df["category"]):
    return list(set(x))
print(f"2. Categories of products: {categories()}")
def min_max(x=df["price"]):
    return f"Min: {np.min(x)} \n Max: {np.max(x)}"
print(f"3. {min_max()}")

1. Average price: 1013.16
2. Categories of products: ['Electronics', 'Music']
3. Min: 29.99 
 Max: 3000.0


## Exercise 2 (NumPy)

In [19]:
# Create an array of all the even integers from 10 to 50
# Hint: check docstring for arange function
array = np.arange(10, 51)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [22]:
# Create a 4x4 matrix with values ranging from 0 to 15
# Hint: use reshape
matrix = np.arange(0,16).reshape(4,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
# Create an array of size 10, filled with random numbers between 0 and 1
random = np.random.rand(10)
print(random)

[0.72288807 0.08415588 0.17672915 0.51690905 0.13924554 0.45326916
 0.37052882 0.68063214 0.58743598 0.49371922]


## Exercise 3 (NumPy)

In [34]:
# Task 1. Create an array of 10 fives

array_5 = np.repeat(5,10)
print(array_5)

[5 5 5 5 5 5 5 5 5 5]


Task 2. Create the following array:

```
       [[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]]
```

In [42]:
# Task 2
array_100 = np.arange(0,1.0,0.01)
print(array_100)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [56]:
# Task 3.

# Create a 5x6 matrix called 'np_matrix' of 30 numbers from 1 to 30

np_matrix = np.arange(1,31).reshape(5,6)
print(np_matrix)

# Select the 2nd row from this matrix and call it row_2...
row_2 = np_matrix[1,:]
print(f"Second row: {row_2}")

# and check the result:
# np.testing.assert_allclose(row_2, np.array([ 7,  8,  9, 10, 11, 12]))

# Select the last column from this matrix and call it last_cal...
last_cal = np_matrix[:,-1]
print(f"Last column: {last_cal}")


# and check the result:
# np.testing.assert_allclose(last_cal, np.array([  6, 12, 18, 24, 30]))

# Using slice extract from np_matrix the following part
np_matrix[2:,1:3]
# array([[14, 15],
#        [20, 21],
#        [26, 27]])



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Second row: [ 7  8  9 10 11 12]
Last column: [ 6 12 18 24 30]


array([[14, 15],
       [20, 21],
       [26, 27]])